# Generated by Django 5.0.1 on 2024-01-29 14:38

import django.db.models.deletion
import registration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('organisation', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Admin_Detail',
            },
        ),
        migrations.CreateModel(
            name='ProductKey',
            fields=[
                ('product_key', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Product_Key',
            },
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_delete',
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(default='BSc.CSIT', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='number',
            field=models.IntegerField(default='98XXXXXXXX'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='product_key',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='profile_photo',
            field=models.ImageField(default='Nophoto', upload_to=registration.models.get_image_path),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='IT-00000', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_name',
            field=models.CharField(default='Ripper', max_length=100),
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teacher_details',
        ),
        migrations.AddField(
            model_name='admindetail',
            name='product_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.productkey'),
        ),
    ]
