# Generated by Django 5.0.1 on 2024-01-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_admindetail_productkey_delete_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='number',
            field=models.IntegerField(default='9800000000', unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(default='IT-00000', max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
